name: CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.17.0'

      - name: Install Dependencies
        run: go get -t -v .

      - name: Run tests
        run: go test -cover -v .
